### ISSUE TITLE
Stairs [Batch 2]

### ISSUE THREAD

**Issue by CruzBishop** [Techern-archived/End-Deco#5]
- [ ] Ensure the End Brick stairs still work [Requires #2]
- [ ] Dyed End Stone Stairs [Requires #4]
- [ ] Dyed End Stone Brick Stairs [Requires #4]
- [ ] Dyed Purpur Stairs [Requires #4]
